### ISSUE TITLE
All logs do not get appended

### ISSUE THREAD

**Issue by chemistry-sourabh** [CCI-MOC/ims#79] opened 2017-02-24 01:17 UTC
Sometimes for some unknown reason logs do not get appended when something goes wrong.

**Comment by ravisantoshgudimetla** [comment] 2017-04-09 01:43
Example and how to reproduce it would be helpful.

**Comment by chemistry-sourabh** [comment] 2017-04-10 04:59
Since @naved001 was able to reproduce this, I will describe what I know.

If some exception is raised which is not caught by BMI like RegistrationFailed or IOError, OSError,etc the logs are printed. This is because the logger typically buffers the logs and writes them after a while.

To fix it we must either catch all exceptions in rpc_server (I Don't Like this as we have to catch Exception) or disable buffering for logger, But the exception that caused the crash won't be printed, except in the console. When we make BMI as service the latter will be an issue as typically stdout is redirected to /dev/null for services.

**Comment by chemistry-sourabh** [comment] 2017-04-10 04:59
@naved001 please describe the exact case.

**Comment by naved001** [comment] 2017-04-13 18:31
@chemistry-sourabh I reproduced this when I deleted the log file. So a new log file was created but logs weren't being written at all.

**Comment by chemistry-sourabh** [comment] 2017-04-13 19:21
@naved001 Did something crash at that time ?

**Comment by pgrosu** [comment] 2017-05-25 15:28
@naved001 Did you get a chance to look into this?  If it's still an issue, could you show us how to replicate it to help with tracing it out.

Thanks,
~p

**Comment by naved001** [comment] 2017-05-25 15:41
@pgrosu last time I checked I couldn't reproduce this issue. Ill have a look at it again.

**Comment by pgrosu** [comment] 2017-05-25 15:44
@naved001 That sounds good, and agree with the double-check.  Thank you for looking into it.

**Comment by naved001** [comment] 2017-05-25 19:17
So far I have not been able to reproduce this issue. 

> If some exception is raised which is not caught by BMI like RegistrationFailed or IOError, OSError,etc the logs are printed

We are now catching these issues (https://github.com/CCI-MOC/ims/pull/116), so maybe that's why we don't run into logging issues. 

@apoorvemohan @ravisantoshgudimetla @chemistry-sourabh @sirushtim should we close this issue then? and what about #106 where we are catching the broad exceptions?

**Comment by pgrosu** [comment] 2017-06-05 19:00
Not yet, still looking into it.

**Comment by chemistry-sourabh** [comment] 2017-06-13 00:21
@pgrosu were you able to reproduce this ?

**Comment by pgrosu** [comment] 2017-06-13 02:17
@chemistry-sourabh Sure let's close it.  How are guys changing the verbosity?

**Comment by naved001** [comment] 2017-07-07 13:48
> @apoorvemohan @ravisantoshgudimetla @chemistry-sourabh @sirushtim should we close this issue then? and what about #106 where we are catching the broad exceptions?

ping

**Comment by chemistry-sourabh** [comment] 2017-07-07 15:59
As I said before it is better to catch the broad exception as logs get dumped if something goes wrong.

If anybody has a way for logs to get dumped without the broad exception then I am all ears.

**Comment by naved001** [comment] 2017-08-01 21:18
We couldn't reproduce this issue so closing it.

**Closed by naved001** 2017-08-01 21:18 UTC
Labels: bug, priority/p1
