### ISSUE TITLE
Don't access the database from the cli

### ISSUE THREAD

**Issue by sirushtim** [CCI-MOC/ims#58] opened 2017-01-29 18:30 UTC
The clients are always supposed to talk to a rest API, never the database. There are a bunch of places where the cli in bmi talks to the database. Iteratively remove them in small easy-to-review patches.

def list_provisioned_nodes(project):
    with BMI(_username, _password, project) as bmi:
def list_projects():
    with BMI(_username, _password, constants.BMI_ADMIN_PROJECT) as bmi:
def add_project(project, network, id):
    with BMI(_username, _password, constants.BMI_ADMIN_PROJECT) as bmi:
def delete_project(project):
    with BMI(_username, _password, constants.BMI_ADMIN_PROJECT) as bmi:
def delete_image(project, img):
    with BMI(_username, _password, constants.BMI_ADMIN_PROJECT) as bmi:
def add_image(project, img, id, snap, parent, public):
    with BMI(_username, _password, constants.BMI_ADMIN_PROJECT) as bmi:
def import_ceph_image(project, img, snap, protect):
    with BMI(_username, _password, project) as bmi:
def export_ceph_image(project, img, name):
    with BMI(_username, _password, project) as bmi:
def copy_image(src_project, img1, dest_project, img2):
    with BMI(_username, _password, src_project) as bmi:
def move_image(src_project, img1, dest_project, img2):
    with BMI(_username, _password, src_project) as bmi:
def get_node_ip(project, node):
    with BMI(_username, _password, project) as bmi:
def create_mapping(project, img):
    with BMI(_username, _password, project) as bmi:
def delete_mapping(project, img):
    with BMI(_username, _password, project) as bmi:

In the end, remove the import of ims.einstein.operations.BMI

**Comment by chemistry-sourabh** [comment] 2017-01-29 18:32
Before this happens the notion of an admin user should be implemented.

**Comment by sirushtim** [comment] 2017-02-01 01:05
@chemistry-sourabh Can you elaborate more on why you think that is necessary for the creation of additional API calls, be it admin or non-admin?

**Comment by chemistry-sourabh** [comment] 2017-02-01 02:11
The reason these calls directly manipulate the DB is because they are admin calls. The normal user shouldn't use them as they may reveal details of other users or manipulate their environment. So since they are directly bound to DB the commands can be run only on the BMI VM which the admin only has access to. So to make everything rest api support for admin users must be implemented first.

**Comment by sirushtim** [comment] 2017-02-01 13:55
I see, I figured since there was a __check_admin() function, we could just implement admin API's, but the function itself does nothing when invoked. Thanks for that.

So now, this bug can convert the non-admin related API calls to be converted to REST API's. There are still a few.

**Comment by chemistry-sourabh** [comment] 2017-02-01 15:41
I left that function for this purpose.

**Comment by chemistry-sourabh** [comment] 2017-02-17 01:16
Duplicate of #46

**Comment by ravisantoshgudimetla** [comment] 2017-02-19 05:12
@chemistry-sourabh , if you think its duplicate, close it off.

**Closed** 2017-02-19 07:29 UTC
Labels: bug, duplicate
